name: Deploy CRM to Vercel

on:
  push:
    branches: [master]
    paths:
      - 'crm/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          cd crm
          npm install -g vercel
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_psxi89Jel2EOYqjUq4inHLq3
          VERCEL_PROJECT_ID: prj_0ZhRH2aAeMeJGq2WQWZS4V2yeQSW
